//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Wandlab.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class WandlabParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		PREPROCESSNAME=1, ARGUMENT=2, STRING=3, POINTER=4, NUMBER=5, COMMENT=6, 
		ALPHA=7, BETA=8, DELTA=9, ZETA=10, ETA=11, LAMBDA=12, MU=13, XI=14, OMICRON=15, 
		PI=16, SIGMA=17, OMEGA=18, GAMMA=19, TAU=20, PHI=21, CHI=22, DASH=23, 
		SLASH=24, POUND=25, COLON=26, SEMICOLON=27, PIPE=28, TICK=29, QUOTE=30, 
		ARROW=31, LBRACKET=32, RBRACKET=33, WS=34;
	public const int
		RULE_program = 0, RULE_operation = 1, RULE_op = 2, RULE_function = 3, 
		RULE_subop = 4, RULE_preprocessor_command = 5, RULE_preprocessor_arg = 6;
	public static readonly string[] ruleNames = {
		"program", "operation", "op", "function", "subop", "preprocessor_command", 
		"preprocessor_arg"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, "'Alpha'", "'Beta'", "'Delta'", 
		"'Zeta'", "'Eta'", "'Lambda'", "'Mu'", "'Xi'", "'Omicron'", "'Pi'", "'Sigma'", 
		"'Omega'", "'Gamma'", "'Tau'", "'Phi'", "'Chi'", "'-'", "'/'", "'#'", 
		"':'", "';'", "'|'", "'^'", "'\"'", "'->'", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "PREPROCESSNAME", "ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", 
		"ALPHA", "BETA", "DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICRON", 
		"PI", "SIGMA", "OMEGA", "GAMMA", "TAU", "PHI", "CHI", "DASH", "SLASH", 
		"POUND", "COLON", "SEMICOLON", "PIPE", "TICK", "QUOTE", "ARROW", "LBRACKET", 
		"RBRACKET", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Wandlab.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static WandlabParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public WandlabParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public WandlabParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(WandlabParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_commandContext[] preprocessor_command() {
			return GetRuleContexts<Preprocessor_commandContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_commandContext preprocessor_command(int i) {
			return GetRuleContext<Preprocessor_commandContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext[] operation() {
			return GetRuleContexts<OperationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext operation(int i) {
			return GetRuleContext<OperationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DASH() { return GetTokens(WandlabParser.DASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DASH(int i) {
			return GetToken(WandlabParser.DASH, i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 17;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==POUND) {
				{
				{
				State = 14;
				preprocessor_command();
				}
				}
				State = 19;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 30;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ALPHA) | (1L << BETA) | (1L << DELTA) | (1L << ZETA) | (1L << ETA) | (1L << LAMBDA) | (1L << MU) | (1L << XI) | (1L << OMICRON) | (1L << PI) | (1L << SIGMA) | (1L << OMEGA))) != 0)) {
				{
				{
				State = 20;
				operation();
				State = 25;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==DASH) {
					{
					{
					State = 21;
					Match(DASH);
					State = 22;
					operation();
					}
					}
					State = 27;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				}
				State = 32;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 33;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpContext op() {
			return GetRuleContext<OpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubopContext subop() {
			return GetRuleContext<SubopContext>(0);
		}
		public OperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterOperation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitOperation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationContext operation() {
		OperationContext _localctx = new OperationContext(Context, State);
		EnterRule(_localctx, 2, RULE_operation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35;
			op();
			State = 37;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TICK) {
				{
				State = 36;
				subop();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ALPHA() { return GetToken(WandlabParser.ALPHA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BETA() { return GetToken(WandlabParser.BETA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DELTA() { return GetToken(WandlabParser.DELTA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PIPE() { return GetTokens(WandlabParser.PIPE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE(int i) {
			return GetToken(WandlabParser.PIPE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ARGUMENT() { return GetTokens(WandlabParser.ARGUMENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARGUMENT(int i) {
			return GetToken(WandlabParser.ARGUMENT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ZETA() { return GetToken(WandlabParser.ZETA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ETA() { return GetToken(WandlabParser.ETA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LAMBDA() { return GetToken(WandlabParser.LAMBDA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MU() { return GetToken(WandlabParser.MU, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode XI() { return GetToken(WandlabParser.XI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OMICRON() { return GetToken(WandlabParser.OMICRON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PI() { return GetToken(WandlabParser.PI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SIGMA() { return GetToken(WandlabParser.SIGMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OMEGA() { return GetToken(WandlabParser.OMEGA, 0); }
		public OpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpContext op() {
		OpContext _localctx = new OpContext(Context, State);
		EnterRule(_localctx, 4, RULE_op);
		try {
			State = 80;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 39;
				Match(ALPHA);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 40;
				Match(BETA);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 41;
				Match(DELTA);
				State = 42;
				Match(PIPE);
				State = 43;
				Match(ARGUMENT);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 44;
				Match(ZETA);
				State = 45;
				Match(PIPE);
				State = 46;
				Match(ARGUMENT);
				State = 47;
				Match(PIPE);
				State = 48;
				Match(ARGUMENT);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 49;
				Match(ETA);
				State = 50;
				Match(PIPE);
				State = 51;
				Match(ARGUMENT);
				State = 52;
				Match(PIPE);
				State = 53;
				Match(ARGUMENT);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 54;
				Match(LAMBDA);
				State = 55;
				function();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 56;
				Match(MU);
				State = 57;
				Match(PIPE);
				State = 58;
				Match(ARGUMENT);
				State = 59;
				Match(PIPE);
				State = 60;
				Match(ARGUMENT);
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 61;
				Match(XI);
				State = 62;
				Match(PIPE);
				State = 63;
				Match(ARGUMENT);
				State = 64;
				Match(PIPE);
				State = 65;
				Match(ARGUMENT);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 66;
				Match(OMICRON);
				State = 67;
				Match(PIPE);
				State = 68;
				Match(ARGUMENT);
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 69;
				Match(PI);
				State = 70;
				Match(PIPE);
				State = 71;
				Match(ARGUMENT);
				State = 72;
				Match(PIPE);
				State = 73;
				Match(ARGUMENT);
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 74;
				Match(SIGMA);
				State = 75;
				function();
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 76;
				Match(OMEGA);
				State = 77;
				Match(PIPE);
				State = 78;
				Match(ARGUMENT);
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 79;
				Match(OMEGA);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(WandlabParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext[] operation() {
			return GetRuleContexts<OperationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext operation(int i) {
			return GetRuleContext<OperationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(WandlabParser.RBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DASH() { return GetTokens(WandlabParser.DASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DASH(int i) {
			return GetToken(WandlabParser.DASH, i);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 6, RULE_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			Match(LBRACKET);
			State = 83;
			operation();
			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DASH) {
				{
				{
				State = 84;
				Match(DASH);
				State = 85;
				operation();
				}
				}
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 91;
			Match(RBRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubopContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TICK() { return GetToken(WandlabParser.TICK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GAMMA() { return GetToken(WandlabParser.GAMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE() { return GetToken(WandlabParser.PIPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARGUMENT() { return GetToken(WandlabParser.ARGUMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAU() { return GetToken(WandlabParser.TAU, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PHI() { return GetToken(WandlabParser.PHI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHI() { return GetToken(WandlabParser.CHI, 0); }
		public SubopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subop; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterSubop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitSubop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubop(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubopContext subop() {
		SubopContext _localctx = new SubopContext(Context, State);
		EnterRule(_localctx, 8, RULE_subop);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			Match(TICK);
			State = 104;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case GAMMA:
				{
				State = 94;
				Match(GAMMA);
				State = 95;
				Match(PIPE);
				State = 96;
				Match(ARGUMENT);
				}
				break;
			case TAU:
				{
				State = 97;
				Match(TAU);
				State = 98;
				Match(PIPE);
				State = 99;
				Match(ARGUMENT);
				}
				break;
			case PHI:
				{
				State = 100;
				Match(PHI);
				}
				break;
			case CHI:
				{
				State = 101;
				Match(CHI);
				State = 102;
				Match(PIPE);
				State = 103;
				Match(ARGUMENT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_commandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POUND() { return GetToken(WandlabParser.POUND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PREPROCESSNAME() { return GetToken(WandlabParser.PREPROCESSNAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(WandlabParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_argContext[] preprocessor_arg() {
			return GetRuleContexts<Preprocessor_argContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_argContext preprocessor_arg(int i) {
			return GetRuleContext<Preprocessor_argContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(WandlabParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PIPE() { return GetTokens(WandlabParser.PIPE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE(int i) {
			return GetToken(WandlabParser.PIPE, i);
		}
		public Preprocessor_commandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterPreprocessor_command(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitPreprocessor_command(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessor_command(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_commandContext preprocessor_command() {
		Preprocessor_commandContext _localctx = new Preprocessor_commandContext(Context, State);
		EnterRule(_localctx, 10, RULE_preprocessor_command);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			Match(POUND);
			State = 107;
			Match(PREPROCESSNAME);
			State = 108;
			Match(COLON);
			State = 109;
			preprocessor_arg();
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PIPE) {
				{
				{
				State = 110;
				Match(PIPE);
				State = 111;
				preprocessor_arg();
				}
				}
				State = 116;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 117;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_argContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARGUMENT() { return GetToken(WandlabParser.ARGUMENT, 0); }
		public Preprocessor_argContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_arg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterPreprocessor_arg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitPreprocessor_arg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessor_arg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_argContext preprocessor_arg() {
		Preprocessor_argContext _localctx = new Preprocessor_argContext(Context, State);
		EnterRule(_localctx, 12, RULE_preprocessor_arg);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 119;
			Match(ARGUMENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '$', '|', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', '\t', 
		'\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', '\x6', 
		'\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', '\x3', 
		'\x2', '\a', '\x2', '\x12', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x15', 
		'\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x1A', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x1D', '\v', '\x2', '\a', '\x2', 
		'\x1F', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\"', '\v', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', '(', '\n', 
		'\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x5', '\x4', 'S', '\n', '\x4', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 'Y', '\n', '\x5', '\f', 
		'\x5', '\xE', '\x5', '\\', '\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', 'k', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 's', '\n', '\a', 
		'\f', '\a', '\xE', '\a', 'v', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x2', '\x2', '\t', '\x2', '\x4', '\x6', 
		'\b', '\n', '\f', '\xE', '\x2', '\x2', '\x2', '\x89', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x4', '%', '\x3', '\x2', '\x2', '\x2', '\x6', 'R', 
		'\x3', '\x2', '\x2', '\x2', '\b', 'T', '\x3', '\x2', '\x2', '\x2', '\n', 
		'_', '\x3', '\x2', '\x2', '\x2', '\f', 'l', '\x3', '\x2', '\x2', '\x2', 
		'\xE', 'y', '\x3', '\x2', '\x2', '\x2', '\x10', '\x12', '\x5', '\f', '\a', 
		'\x2', '\x11', '\x10', '\x3', '\x2', '\x2', '\x2', '\x12', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x11', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x14', '\x3', '\x2', '\x2', '\x2', '\x14', ' ', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '\x13', '\x3', '\x2', '\x2', '\x2', '\x16', '\x1B', '\x5', 
		'\x4', '\x3', '\x2', '\x17', '\x18', '\a', '\x19', '\x2', '\x2', '\x18', 
		'\x1A', '\x5', '\x4', '\x3', '\x2', '\x19', '\x17', '\x3', '\x2', '\x2', 
		'\x2', '\x1A', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1C', 
		'\x1F', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\x16', '\x3', '\x2', '\x2', '\x2', '\x1F', '\"', '\x3', 
		'\x2', '\x2', '\x2', ' ', '\x1E', '\x3', '\x2', '\x2', '\x2', ' ', '!', 
		'\x3', '\x2', '\x2', '\x2', '!', '#', '\x3', '\x2', '\x2', '\x2', '\"', 
		' ', '\x3', '\x2', '\x2', '\x2', '#', '$', '\a', '\x2', '\x2', '\x3', 
		'$', '\x3', '\x3', '\x2', '\x2', '\x2', '%', '\'', '\x5', '\x6', '\x4', 
		'\x2', '&', '(', '\x5', '\n', '\x6', '\x2', '\'', '&', '\x3', '\x2', '\x2', 
		'\x2', '\'', '(', '\x3', '\x2', '\x2', '\x2', '(', '\x5', '\x3', '\x2', 
		'\x2', '\x2', ')', 'S', '\a', '\t', '\x2', '\x2', '*', 'S', '\a', '\n', 
		'\x2', '\x2', '+', ',', '\a', '\v', '\x2', '\x2', ',', '-', '\a', '\x1E', 
		'\x2', '\x2', '-', 'S', '\a', '\x4', '\x2', '\x2', '.', '/', '\a', '\f', 
		'\x2', '\x2', '/', '\x30', '\a', '\x1E', '\x2', '\x2', '\x30', '\x31', 
		'\a', '\x4', '\x2', '\x2', '\x31', '\x32', '\a', '\x1E', '\x2', '\x2', 
		'\x32', 'S', '\a', '\x4', '\x2', '\x2', '\x33', '\x34', '\a', '\r', '\x2', 
		'\x2', '\x34', '\x35', '\a', '\x1E', '\x2', '\x2', '\x35', '\x36', '\a', 
		'\x4', '\x2', '\x2', '\x36', '\x37', '\a', '\x1E', '\x2', '\x2', '\x37', 
		'S', '\a', '\x4', '\x2', '\x2', '\x38', '\x39', '\a', '\xE', '\x2', '\x2', 
		'\x39', 'S', '\x5', '\b', '\x5', '\x2', ':', ';', '\a', '\xF', '\x2', 
		'\x2', ';', '<', '\a', '\x1E', '\x2', '\x2', '<', '=', '\a', '\x4', '\x2', 
		'\x2', '=', '>', '\a', '\x1E', '\x2', '\x2', '>', 'S', '\a', '\x4', '\x2', 
		'\x2', '?', '@', '\a', '\x10', '\x2', '\x2', '@', '\x41', '\a', '\x1E', 
		'\x2', '\x2', '\x41', '\x42', '\a', '\x4', '\x2', '\x2', '\x42', '\x43', 
		'\a', '\x1E', '\x2', '\x2', '\x43', 'S', '\a', '\x4', '\x2', '\x2', '\x44', 
		'\x45', '\a', '\x11', '\x2', '\x2', '\x45', '\x46', '\a', '\x1E', '\x2', 
		'\x2', '\x46', 'S', '\a', '\x4', '\x2', '\x2', 'G', 'H', '\a', '\x12', 
		'\x2', '\x2', 'H', 'I', '\a', '\x1E', '\x2', '\x2', 'I', 'J', '\a', '\x4', 
		'\x2', '\x2', 'J', 'K', '\a', '\x1E', '\x2', '\x2', 'K', 'S', '\a', '\x4', 
		'\x2', '\x2', 'L', 'M', '\a', '\x13', '\x2', '\x2', 'M', 'S', '\x5', '\b', 
		'\x5', '\x2', 'N', 'O', '\a', '\x14', '\x2', '\x2', 'O', 'P', '\a', '\x1E', 
		'\x2', '\x2', 'P', 'S', '\a', '\x4', '\x2', '\x2', 'Q', 'S', '\a', '\x14', 
		'\x2', '\x2', 'R', ')', '\x3', '\x2', '\x2', '\x2', 'R', '*', '\x3', '\x2', 
		'\x2', '\x2', 'R', '+', '\x3', '\x2', '\x2', '\x2', 'R', '.', '\x3', '\x2', 
		'\x2', '\x2', 'R', '\x33', '\x3', '\x2', '\x2', '\x2', 'R', '\x38', '\x3', 
		'\x2', '\x2', '\x2', 'R', ':', '\x3', '\x2', '\x2', '\x2', 'R', '?', '\x3', 
		'\x2', '\x2', '\x2', 'R', '\x44', '\x3', '\x2', '\x2', '\x2', 'R', 'G', 
		'\x3', '\x2', '\x2', '\x2', 'R', 'L', '\x3', '\x2', '\x2', '\x2', 'R', 
		'N', '\x3', '\x2', '\x2', '\x2', 'R', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'S', '\a', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\a', '\"', '\x2', '\x2', 
		'U', 'Z', '\x5', '\x4', '\x3', '\x2', 'V', 'W', '\a', '\x19', '\x2', '\x2', 
		'W', 'Y', '\x5', '\x4', '\x3', '\x2', 'X', 'V', '\x3', '\x2', '\x2', '\x2', 
		'Y', '\\', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', ']', '\x3', '\x2', '\x2', 
		'\x2', '\\', 'Z', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', '#', '\x2', 
		'\x2', '^', '\t', '\x3', '\x2', '\x2', '\x2', '_', 'j', '\a', '\x1F', 
		'\x2', '\x2', '`', '\x61', '\a', '\x15', '\x2', '\x2', '\x61', '\x62', 
		'\a', '\x1E', '\x2', '\x2', '\x62', 'k', '\a', '\x4', '\x2', '\x2', '\x63', 
		'\x64', '\a', '\x16', '\x2', '\x2', '\x64', '\x65', '\a', '\x1E', '\x2', 
		'\x2', '\x65', 'k', '\a', '\x4', '\x2', '\x2', '\x66', 'k', '\a', '\x17', 
		'\x2', '\x2', 'g', 'h', '\a', '\x18', '\x2', '\x2', 'h', 'i', '\a', '\x1E', 
		'\x2', '\x2', 'i', 'k', '\a', '\x4', '\x2', '\x2', 'j', '`', '\x3', '\x2', 
		'\x2', '\x2', 'j', '\x63', '\x3', '\x2', '\x2', '\x2', 'j', '\x66', '\x3', 
		'\x2', '\x2', '\x2', 'j', 'g', '\x3', '\x2', '\x2', '\x2', 'k', '\v', 
		'\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '\x1B', '\x2', '\x2', 'm', 
		'n', '\a', '\x3', '\x2', '\x2', 'n', 'o', '\a', '\x1C', '\x2', '\x2', 
		'o', 't', '\x5', '\xE', '\b', '\x2', 'p', 'q', '\a', '\x1E', '\x2', '\x2', 
		'q', 's', '\x5', '\xE', '\b', '\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 
		's', 'v', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 
		't', 'u', '\x3', '\x2', '\x2', '\x2', 'u', 'w', '\x3', '\x2', '\x2', '\x2', 
		'v', 't', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '\x1D', '\x2', '\x2', 
		'x', '\r', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\x4', '\x2', '\x2', 
		'z', '\xF', '\x3', '\x2', '\x2', '\x2', '\n', '\x13', '\x1B', ' ', '\'', 
		'R', 'Z', 'j', 't',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
