//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Wandlab.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class WandlabLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		PREPROCESSNAME=1, ARGUMENT=2, STRING=3, POINTER=4, NUMBER=5, COMMENT=6, 
		ALPHA=7, BETA=8, DELTA=9, ZETA=10, ETA=11, LAMBDA=12, MU=13, XI=14, OMICRON=15, 
		PI=16, SIGMA=17, OMEGA=18, GAMMA=19, TAU=20, PHI=21, CHI=22, DASH=23, 
		SLASH=24, POUND=25, COLON=26, SEMICOLON=27, PIPE=28, TICK=29, QUOTE=30, 
		ARROW=31, LBRACKET=32, RBRACKET=33, WS=34;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"PREPROCESSNAME", "ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", 
		"ALPHA", "BETA", "DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICRON", 
		"PI", "SIGMA", "OMEGA", "GAMMA", "TAU", "PHI", "CHI", "DASH", "SLASH", 
		"POUND", "COLON", "SEMICOLON", "PIPE", "TICK", "QUOTE", "ARROW", "LBRACKET", 
		"RBRACKET", "WS"
	};


	public WandlabLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public WandlabLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, "'Alpha'", "'Beta'", "'Delta'", 
		"'Zeta'", "'Eta'", "'Lambda'", "'Mu'", "'Xi'", "'Omicron'", "'Pi'", "'Sigma'", 
		"'Omega'", "'Gamma'", "'Tau'", "'Phi'", "'Chi'", "'-'", "'/'", "'#'", 
		"':'", "';'", "'|'", "'^'", "'\"'", "'->'", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "PREPROCESSNAME", "ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", 
		"ALPHA", "BETA", "DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICRON", 
		"PI", "SIGMA", "OMEGA", "GAMMA", "TAU", "PHI", "CHI", "DASH", "SLASH", 
		"POUND", "COLON", "SEMICOLON", "PIPE", "TICK", "QUOTE", "ARROW", "LBRACKET", 
		"RBRACKET", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Wandlab.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static WandlabLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '$', '\xDC', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x3', '\x2', '\x6', '\x2', 'I', '\n', '\x2', '\r', '\x2', 
		'\xE', '\x2', 'J', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', '\x3', 
		'P', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 'T', '\n', 
		'\x4', '\f', '\x4', '\xE', '\x4', 'W', '\v', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x6', '\x5', '\\', '\n', '\x5', '\r', '\x5', '\xE', 
		'\x5', ']', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x6', '\x6', '\x63', 
		'\n', '\x6', '\r', '\x6', '\xE', '\x6', '\x64', '\x3', '\a', '\x3', '\a', 
		'\a', '\a', 'i', '\n', '\a', '\f', '\a', '\xE', '\a', 'l', '\v', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', '!', 
		'\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', '#', 
		'\x3', '#', '\x4', 'U', 'j', '\x2', '$', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', 
		'\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', 
		';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', '#', '\x45', '$', 
		'\x3', '\x2', '\x5', '\x4', '\x2', '\x43', '\\', '\x61', '\x61', '\x3', 
		'\x2', '\x32', ';', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', 
		'\x2', '\xE2', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x3', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\x5', 'O', '\x3', '\x2', '\x2', '\x2', '\a', 'Q', '\x3', 
		'\x2', '\x2', '\x2', '\t', '[', '\x3', '\x2', '\x2', '\x2', '\v', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x66', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'q', '\x3', '\x2', '\x2', '\x2', '\x11', 'w', '\x3', '\x2', '\x2', 
		'\x2', '\x13', '|', '\x3', '\x2', '\x2', '\x2', '\x15', '\x82', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '\x87', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x95', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '!', '\xA0', '\x3', '\x2', '\x2', '\x2', '#', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '%', '\xA9', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', ')', '\xB5', '\x3', '\x2', '\x2', 
		'\x2', '+', '\xB9', '\x3', '\x2', '\x2', '\x2', '-', '\xBD', '\x3', '\x2', 
		'\x2', '\x2', '/', '\xC1', '\x3', '\x2', '\x2', '\x2', '\x31', '\xC3', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xC5', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xC7', '\x3', '\x2', '\x2', '\x2', '\x37', '\xC9', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xCB', '\x3', '\x2', '\x2', '\x2', ';', '\xCD', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xCF', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xD1', '\x3', '\x2', '\x2', '\x2', '\x41', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xD6', '\x3', '\x2', '\x2', '\x2', '\x45', '\xD8', '\x3', 
		'\x2', '\x2', '\x2', 'G', 'I', '\t', '\x2', '\x2', '\x2', 'H', 'G', '\x3', 
		'\x2', '\x2', '\x2', 'I', 'J', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', 
		'\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', '\x4', 
		'\x3', '\x2', '\x2', '\x2', 'L', 'P', '\x5', '\a', '\x4', '\x2', 'M', 
		'P', '\x5', '\t', '\x5', '\x2', 'N', 'P', '\x5', '\v', '\x6', '\x2', 'O', 
		'L', '\x3', '\x2', '\x2', '\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 
		'O', 'N', '\x3', '\x2', '\x2', '\x2', 'P', '\x6', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'U', '\x5', '=', '\x1F', '\x2', 'R', 'T', '\v', '\x2', '\x2', 
		'\x2', 'S', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\x3', '\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', 
		'\x2', 'V', 'X', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\x5', '=', '\x1F', '\x2', 'Y', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '\\', '\x5', '?', ' ', '\x2', '[', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', 
		'\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', 
		'\x2', '\x2', '_', '`', '\x5', '\v', '\x6', '\x2', '`', '\n', '\x3', '\x2', 
		'\x2', '\x2', '\x61', '\x63', '\t', '\x3', '\x2', '\x2', '\x62', '\x61', 
		'\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\x64', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\x3', '\x2', 
		'\x2', '\x2', '\x65', '\f', '\x3', '\x2', '\x2', '\x2', '\x66', 'j', '\x5', 
		'\x31', '\x19', '\x2', 'g', 'i', '\v', '\x2', '\x2', '\x2', 'h', 'g', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'l', '\x3', '\x2', '\x2', '\x2', 'j', 
		'k', '\x3', '\x2', '\x2', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 
		'k', 'm', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'm', 'n', '\x5', '\x31', '\x19', '\x2', 'n', 'o', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\b', '\a', '\x2', '\x2', 'p', '\xE', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\a', '\x43', '\x2', '\x2', 'r', 's', '\a', 'n', '\x2', 
		'\x2', 's', 't', '\a', 'r', '\x2', '\x2', 't', 'u', '\a', 'j', '\x2', 
		'\x2', 'u', 'v', '\a', '\x63', '\x2', '\x2', 'v', '\x10', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'x', '\a', '\x44', '\x2', '\x2', 'x', 'y', '\a', 'g', 
		'\x2', '\x2', 'y', 'z', '\a', 'v', '\x2', '\x2', 'z', '{', '\a', '\x63', 
		'\x2', '\x2', '{', '\x12', '\x3', '\x2', '\x2', '\x2', '|', '}', '\a', 
		'\x46', '\x2', '\x2', '}', '~', '\a', 'g', '\x2', '\x2', '~', '\x7F', 
		'\a', 'n', '\x2', '\x2', '\x7F', '\x80', '\a', 'v', '\x2', '\x2', '\x80', 
		'\x81', '\a', '\x63', '\x2', '\x2', '\x81', '\x14', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\a', '\\', '\x2', '\x2', '\x83', '\x84', '\a', 
		'g', '\x2', '\x2', '\x84', '\x85', '\a', 'v', '\x2', '\x2', '\x85', '\x86', 
		'\a', '\x63', '\x2', '\x2', '\x86', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x88', '\a', 'G', '\x2', '\x2', '\x88', '\x89', '\a', 'v', '\x2', 
		'\x2', '\x89', '\x8A', '\a', '\x63', '\x2', '\x2', '\x8A', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x8B', '\x8C', '\a', 'N', '\x2', '\x2', '\x8C', 
		'\x8D', '\a', '\x63', '\x2', '\x2', '\x8D', '\x8E', '\a', 'o', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', '\x64', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'\x66', '\x2', '\x2', '\x90', '\x91', '\a', '\x63', '\x2', '\x2', '\x91', 
		'\x1A', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\a', 'O', '\x2', 
		'\x2', '\x93', '\x94', '\a', 'w', '\x2', '\x2', '\x94', '\x1C', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x96', '\a', 'Z', '\x2', '\x2', '\x96', 
		'\x97', '\a', 'k', '\x2', '\x2', '\x97', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x98', '\x99', '\a', 'Q', '\x2', '\x2', '\x99', '\x9A', '\a', 
		'o', '\x2', '\x2', '\x9A', '\x9B', '\a', 'k', '\x2', '\x2', '\x9B', '\x9C', 
		'\a', '\x65', '\x2', '\x2', '\x9C', '\x9D', '\a', 't', '\x2', '\x2', '\x9D', 
		'\x9E', '\a', 'q', '\x2', '\x2', '\x9E', '\x9F', '\a', 'p', '\x2', '\x2', 
		'\x9F', ' ', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', 'R', '\x2', 
		'\x2', '\xA1', '\xA2', '\a', 'k', '\x2', '\x2', '\xA2', '\"', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA4', '\a', 'U', '\x2', '\x2', '\xA4', '\xA5', 
		'\a', 'k', '\x2', '\x2', '\xA5', '\xA6', '\a', 'i', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', 'o', '\x2', '\x2', '\xA7', '\xA8', '\a', '\x63', '\x2', 
		'\x2', '\xA8', '$', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\a', 
		'Q', '\x2', '\x2', '\xAA', '\xAB', '\a', 'o', '\x2', '\x2', '\xAB', '\xAC', 
		'\a', 'g', '\x2', '\x2', '\xAC', '\xAD', '\a', 'i', '\x2', '\x2', '\xAD', 
		'\xAE', '\a', '\x63', '\x2', '\x2', '\xAE', '&', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\a', 'I', '\x2', '\x2', '\xB0', '\xB1', '\a', 
		'\x63', '\x2', '\x2', '\xB1', '\xB2', '\a', 'o', '\x2', '\x2', '\xB2', 
		'\xB3', '\a', 'o', '\x2', '\x2', '\xB3', '\xB4', '\a', '\x63', '\x2', 
		'\x2', '\xB4', '(', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\a', 
		'V', '\x2', '\x2', '\xB6', '\xB7', '\a', '\x63', '\x2', '\x2', '\xB7', 
		'\xB8', '\a', 'w', '\x2', '\x2', '\xB8', '*', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xBA', '\a', 'R', '\x2', '\x2', '\xBA', '\xBB', '\a', 'j', '\x2', 
		'\x2', '\xBB', '\xBC', '\a', 'k', '\x2', '\x2', '\xBC', ',', '\x3', '\x2', 
		'\x2', '\x2', '\xBD', '\xBE', '\a', '\x45', '\x2', '\x2', '\xBE', '\xBF', 
		'\a', 'j', '\x2', '\x2', '\xBF', '\xC0', '\a', 'k', '\x2', '\x2', '\xC0', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', '\a', '/', '\x2', '\x2', 
		'\xC2', '\x30', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\a', '\x31', 
		'\x2', '\x2', '\xC4', '\x32', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', 
		'\a', '%', '\x2', '\x2', '\xC6', '\x34', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC8', '\a', '<', '\x2', '\x2', '\xC8', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\a', '=', '\x2', '\x2', '\xCA', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', '~', '\x2', '\x2', '\xCC', 
		':', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\a', '`', '\x2', '\x2', 
		'\xCE', '<', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\a', '$', '\x2', 
		'\x2', '\xD0', '>', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', '\a', 
		'/', '\x2', '\x2', '\xD2', '\xD3', '\a', '@', '\x2', '\x2', '\xD3', '@', 
		'\x3', '\x2', '\x2', '\x2', '\xD4', '\xD5', '\a', ']', '\x2', '\x2', '\xD5', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\a', '_', '\x2', 
		'\x2', '\xD7', '\x44', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', '\t', 
		'\x4', '\x2', '\x2', '\xD9', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xDA', 
		'\xDB', '\b', '#', '\x2', '\x2', '\xDB', '\x46', '\x3', '\x2', '\x2', 
		'\x2', '\t', '\x2', 'J', 'O', 'U', ']', '\x64', 'j', '\x3', '\b', '\x2', 
		'\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
