//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Wandlab.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class WandlabLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ARGUMENT=1, STRING=2, POINTER=3, NUMBER=4, COMMENT=5, ALPHA=6, BETA=7, 
		DELTA=8, ZETA=9, ETA=10, LAMBDA=11, MU=12, XI=13, OMICORN=14, PI=15, SIGMA=16, 
		OMEGA=17, GAMMA=18, TAU=19, PHI=20, CHI=21, DASH=22, SLASH=23, PIPE=24, 
		TICK=25, QUOTE=26, ARROW=27, LBRACKET=28, RBRACKET=29, WS=30;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", "ALPHA", "BETA", 
		"DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICORN", "PI", "SIGMA", 
		"OMEGA", "GAMMA", "TAU", "PHI", "CHI", "DASH", "SLASH", "PIPE", "TICK", 
		"QUOTE", "ARROW", "LBRACKET", "RBRACKET", "WS"
	};


	public WandlabLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public WandlabLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, "'Alpha'", "'Beta'", "'Delta'", "'Zeta'", 
		"'Eta'", "'Lambda'", "'Mu'", "'Xi'", "'Omicorn'", "'Pi'", "'Sigma'", "'Omega'", 
		"'Gamma'", "'Tau'", "'Phi'", "'Chi'", "'-'", "'/'", "'|'", "'^'", "'\"'", 
		"'->'", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", "ALPHA", "BETA", 
		"DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICORN", "PI", "SIGMA", 
		"OMEGA", "GAMMA", "TAU", "PHI", "CHI", "DASH", "SLASH", "PIPE", "TICK", 
		"QUOTE", "ARROW", "LBRACKET", "RBRACKET", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Wandlab.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static WandlabLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', ' ', '\xC9', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x5', '\x2', '\x43', '\n', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\a', '\x3', 'G', '\n', '\x3', '\f', '\x3', 
		'\xE', '\x3', 'J', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x6', '\x4', 'O', '\n', '\x4', '\r', '\x4', '\xE', '\x4', 'P', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x6', '\x5', 'V', '\n', '\x5', '\r', 
		'\x5', '\xE', '\x5', 'W', '\x3', '\x6', '\x3', '\x6', '\a', '\x6', '\\', 
		'\n', '\x6', '\f', '\x6', '\xE', '\x6', '_', '\v', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', 
		'\x4', 'H', ']', '\x2', ' ', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '=', 
		' ', '\x3', '\x2', '\x4', '\x3', '\x2', '\x32', ';', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x2', '\xCE', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x3', '\x42', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x44', '\x3', '\x2', '\x2', '\x2', '\a', 'N', '\x3', 
		'\x2', '\x2', '\x2', '\t', 'U', '\x3', '\x2', '\x2', '\x2', '\v', 'Y', 
		'\x3', '\x2', '\x2', '\x2', '\r', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'j', '\x3', '\x2', '\x2', '\x2', '\x11', 'o', '\x3', '\x2', '\x2', 
		'\x2', '\x13', 'u', '\x3', '\x2', '\x2', '\x2', '\x15', 'z', '\x3', '\x2', 
		'\x2', '\x2', '\x17', '~', '\x3', '\x2', '\x2', '\x2', '\x19', '\x85', 
		'\x3', '\x2', '\x2', '\x2', '\x1B', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '!', '\x96', '\x3', '\x2', '\x2', '\x2', '#', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '%', '\xA2', '\x3', '\x2', '\x2', '\x2', '\'', '\xA8', 
		'\x3', '\x2', '\x2', '\x2', ')', '\xAC', '\x3', '\x2', '\x2', '\x2', '+', 
		'\xB0', '\x3', '\x2', '\x2', '\x2', '-', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '/', '\xB6', '\x3', '\x2', '\x2', '\x2', '\x31', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\xBA', '\x3', '\x2', '\x2', '\x2', '\x35', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\x37', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\x39', '\xC1', '\x3', '\x2', '\x2', '\x2', ';', '\xC3', '\x3', 
		'\x2', '\x2', '\x2', '=', '\xC5', '\x3', '\x2', '\x2', '\x2', '?', '\x43', 
		'\x5', '\x5', '\x3', '\x2', '@', '\x43', '\x5', '\a', '\x4', '\x2', '\x41', 
		'\x43', '\x5', '\t', '\x5', '\x2', '\x42', '?', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '@', '\x3', '\x2', '\x2', '\x2', '\x42', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x43', '\x4', '\x3', '\x2', '\x2', '\x2', '\x44', 'H', 
		'\x5', '\x35', '\x1B', '\x2', '\x45', 'G', '\v', '\x2', '\x2', '\x2', 
		'\x46', '\x45', '\x3', '\x2', '\x2', '\x2', 'G', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'H', 'I', '\x3', '\x2', '\x2', '\x2', 'H', '\x46', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'K', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', 
		'\x2', '\x2', 'K', 'L', '\x5', '\x35', '\x1B', '\x2', 'L', '\x6', '\x3', 
		'\x2', '\x2', '\x2', 'M', 'O', '\x5', '\x37', '\x1C', '\x2', 'N', 'M', 
		'\x3', '\x2', '\x2', '\x2', 'O', 'P', '\x3', '\x2', '\x2', '\x2', 'P', 
		'N', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x5', '\t', '\x5', '\x2', 
		'S', '\b', '\x3', '\x2', '\x2', '\x2', 'T', 'V', '\t', '\x2', '\x2', '\x2', 
		'U', 'T', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\x3', '\x2', '\x2', '\x2', 
		'W', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', '\x2', 
		'X', '\n', '\x3', '\x2', '\x2', '\x2', 'Y', ']', '\x5', '/', '\x18', '\x2', 
		'Z', '\\', '\v', '\x2', '\x2', '\x2', '[', 'Z', '\x3', '\x2', '\x2', '\x2', 
		'\\', '_', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', 
		'\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', '`', '\x3', '\x2', '\x2', 
		'\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x5', '/', 
		'\x18', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\b', '\x6', '\x2', '\x2', '\x63', '\f', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\a', '\x43', '\x2', '\x2', '\x65', '\x66', '\a', 'n', '\x2', 
		'\x2', '\x66', 'g', '\a', 'r', '\x2', '\x2', 'g', 'h', '\a', 'j', '\x2', 
		'\x2', 'h', 'i', '\a', '\x63', '\x2', '\x2', 'i', '\xE', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\a', '\x44', '\x2', '\x2', 'k', 'l', '\a', 'g', 
		'\x2', '\x2', 'l', 'm', '\a', 'v', '\x2', '\x2', 'm', 'n', '\a', '\x63', 
		'\x2', '\x2', 'n', '\x10', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\a', 
		'\x46', '\x2', '\x2', 'p', 'q', '\a', 'g', '\x2', '\x2', 'q', 'r', '\a', 
		'n', '\x2', '\x2', 'r', 's', '\a', 'v', '\x2', '\x2', 's', 't', '\a', 
		'\x63', '\x2', '\x2', 't', '\x12', '\x3', '\x2', '\x2', '\x2', 'u', 'v', 
		'\a', '\\', '\x2', '\x2', 'v', 'w', '\a', 'g', '\x2', '\x2', 'w', 'x', 
		'\a', 'v', '\x2', '\x2', 'x', 'y', '\a', '\x63', '\x2', '\x2', 'y', '\x14', 
		'\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', 'G', '\x2', '\x2', '{', '|', 
		'\a', 'v', '\x2', '\x2', '|', '}', '\a', '\x63', '\x2', '\x2', '}', '\x16', 
		'\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\a', 'N', '\x2', '\x2', '\x7F', 
		'\x80', '\a', '\x63', '\x2', '\x2', '\x80', '\x81', '\a', 'o', '\x2', 
		'\x2', '\x81', '\x82', '\a', '\x64', '\x2', '\x2', '\x82', '\x83', '\a', 
		'\x66', '\x2', '\x2', '\x83', '\x84', '\a', '\x63', '\x2', '\x2', '\x84', 
		'\x18', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\a', 'O', '\x2', 
		'\x2', '\x86', '\x87', '\a', 'w', '\x2', '\x2', '\x87', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x88', '\x89', '\a', 'Z', '\x2', '\x2', '\x89', 
		'\x8A', '\a', 'k', '\x2', '\x2', '\x8A', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x8C', '\a', 'Q', '\x2', '\x2', '\x8C', '\x8D', '\a', 
		'o', '\x2', '\x2', '\x8D', '\x8E', '\a', 'k', '\x2', '\x2', '\x8E', '\x8F', 
		'\a', '\x65', '\x2', '\x2', '\x8F', '\x90', '\a', 'q', '\x2', '\x2', '\x90', 
		'\x91', '\a', 't', '\x2', '\x2', '\x91', '\x92', '\a', 'p', '\x2', '\x2', 
		'\x92', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\a', 'R', 
		'\x2', '\x2', '\x94', '\x95', '\a', 'k', '\x2', '\x2', '\x95', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\x96', '\x97', '\a', 'U', '\x2', '\x2', '\x97', 
		'\x98', '\a', 'k', '\x2', '\x2', '\x98', '\x99', '\a', 'i', '\x2', '\x2', 
		'\x99', '\x9A', '\a', 'o', '\x2', '\x2', '\x9A', '\x9B', '\a', '\x63', 
		'\x2', '\x2', '\x9B', '\"', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', 
		'\a', 'Q', '\x2', '\x2', '\x9D', '\x9E', '\a', 'o', '\x2', '\x2', '\x9E', 
		'\x9F', '\a', 'g', '\x2', '\x2', '\x9F', '\xA0', '\a', 'i', '\x2', '\x2', 
		'\xA0', '\xA1', '\a', '\x63', '\x2', '\x2', '\xA1', '$', '\x3', '\x2', 
		'\x2', '\x2', '\xA2', '\xA3', '\a', 'I', '\x2', '\x2', '\xA3', '\xA4', 
		'\a', '\x63', '\x2', '\x2', '\xA4', '\xA5', '\a', 'o', '\x2', '\x2', '\xA5', 
		'\xA6', '\a', 'o', '\x2', '\x2', '\xA6', '\xA7', '\a', '\x63', '\x2', 
		'\x2', '\xA7', '&', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\a', 
		'V', '\x2', '\x2', '\xA9', '\xAA', '\a', '\x63', '\x2', '\x2', '\xAA', 
		'\xAB', '\a', 'w', '\x2', '\x2', '\xAB', '(', '\x3', '\x2', '\x2', '\x2', 
		'\xAC', '\xAD', '\a', 'R', '\x2', '\x2', '\xAD', '\xAE', '\a', 'j', '\x2', 
		'\x2', '\xAE', '\xAF', '\a', 'k', '\x2', '\x2', '\xAF', '*', '\x3', '\x2', 
		'\x2', '\x2', '\xB0', '\xB1', '\a', '\x45', '\x2', '\x2', '\xB1', '\xB2', 
		'\a', 'j', '\x2', '\x2', '\xB2', '\xB3', '\a', 'k', '\x2', '\x2', '\xB3', 
		',', '\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\a', '/', '\x2', '\x2', 
		'\xB5', '.', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\a', '\x31', 
		'\x2', '\x2', '\xB7', '\x30', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xB9', 
		'\a', '~', '\x2', '\x2', '\xB9', '\x32', '\x3', '\x2', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', '`', '\x2', '\x2', '\xBB', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xBD', '\a', '$', '\x2', '\x2', '\xBD', '\x36', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xBF', '\a', '/', '\x2', '\x2', '\xBF', 
		'\xC0', '\a', '@', '\x2', '\x2', '\xC0', '\x38', '\x3', '\x2', '\x2', 
		'\x2', '\xC1', '\xC2', '\a', ']', '\x2', '\x2', '\xC2', ':', '\x3', '\x2', 
		'\x2', '\x2', '\xC3', '\xC4', '\a', '_', '\x2', '\x2', '\xC4', '<', '\x3', 
		'\x2', '\x2', '\x2', '\xC5', '\xC6', '\t', '\x3', '\x2', '\x2', '\xC6', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\b', '\x1F', '\x2', 
		'\x2', '\xC8', '>', '\x3', '\x2', '\x2', '\x2', '\b', '\x2', '\x42', 'H', 
		'P', 'W', ']', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
