//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Wandlab.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class WandlabParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ARGUMENT=1, STRING=2, POINTER=3, NUMBER=4, COMMENT=5, ALPHA=6, BETA=7, 
		DELTA=8, ZETA=9, ETA=10, LAMBDA=11, MU=12, XI=13, OMICORN=14, PI=15, SIGMA=16, 
		OMEGA=17, GAMMA=18, TAU=19, PHI=20, CHI=21, PREPROCESSNAME=22, PREPROCESSARG=23, 
		DASH=24, SLASH=25, POUND=26, COLON=27, SEMICOLON=28, PIPE=29, TICK=30, 
		QUOTE=31, ARROW=32, LBRACKET=33, RBRACKET=34, WS=35;
	public const int
		RULE_program = 0, RULE_operation = 1, RULE_op = 2, RULE_function = 3, 
		RULE_subop = 4, RULE_preprocessor_command = 5;
	public static readonly string[] ruleNames = {
		"program", "operation", "op", "function", "subop", "preprocessor_command"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, "'Alpha'", "'Beta'", "'Delta'", "'Zeta'", 
		"'Eta'", "'Lambda'", "'Mu'", "'Xi'", "'Omicorn'", "'Pi'", "'Sigma'", "'Omega'", 
		"'Gamma'", "'Tau'", "'Phi'", "'Chi'", null, null, "'-'", "'/'", "'#'", 
		"':'", "';'", "'|'", "'^'", "'\"'", "'->'", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", "ALPHA", "BETA", 
		"DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICORN", "PI", "SIGMA", 
		"OMEGA", "GAMMA", "TAU", "PHI", "CHI", "PREPROCESSNAME", "PREPROCESSARG", 
		"DASH", "SLASH", "POUND", "COLON", "SEMICOLON", "PIPE", "TICK", "QUOTE", 
		"ARROW", "LBRACKET", "RBRACKET", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Wandlab.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static WandlabParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public WandlabParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public WandlabParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(WandlabParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_commandContext[] preprocessor_command() {
			return GetRuleContexts<Preprocessor_commandContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Preprocessor_commandContext preprocessor_command(int i) {
			return GetRuleContext<Preprocessor_commandContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext[] operation() {
			return GetRuleContexts<OperationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext operation(int i) {
			return GetRuleContext<OperationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DASH() { return GetTokens(WandlabParser.DASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DASH(int i) {
			return GetToken(WandlabParser.DASH, i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 15;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==POUND) {
				{
				{
				State = 12;
				preprocessor_command();
				}
				}
				State = 17;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 28;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ALPHA) | (1L << BETA) | (1L << DELTA) | (1L << ZETA) | (1L << ETA) | (1L << LAMBDA) | (1L << MU) | (1L << XI) | (1L << OMICORN) | (1L << PI) | (1L << SIGMA) | (1L << OMEGA))) != 0)) {
				{
				{
				State = 18;
				operation();
				State = 23;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==DASH) {
					{
					{
					State = 19;
					Match(DASH);
					State = 20;
					operation();
					}
					}
					State = 25;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				}
				State = 30;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 31;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OpContext op() {
			return GetRuleContext<OpContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SubopContext subop() {
			return GetRuleContext<SubopContext>(0);
		}
		public OperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operation; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterOperation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitOperation(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationContext operation() {
		OperationContext _localctx = new OperationContext(Context, State);
		EnterRule(_localctx, 2, RULE_operation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 33;
			op();
			State = 35;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==TICK) {
				{
				State = 34;
				subop();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OpContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ALPHA() { return GetToken(WandlabParser.ALPHA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BETA() { return GetToken(WandlabParser.BETA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DELTA() { return GetToken(WandlabParser.DELTA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PIPE() { return GetTokens(WandlabParser.PIPE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE(int i) {
			return GetToken(WandlabParser.PIPE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ARGUMENT() { return GetTokens(WandlabParser.ARGUMENT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARGUMENT(int i) {
			return GetToken(WandlabParser.ARGUMENT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ZETA() { return GetToken(WandlabParser.ZETA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ETA() { return GetToken(WandlabParser.ETA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LAMBDA() { return GetToken(WandlabParser.LAMBDA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionContext function() {
			return GetRuleContext<FunctionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MU() { return GetToken(WandlabParser.MU, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode XI() { return GetToken(WandlabParser.XI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OMICORN() { return GetToken(WandlabParser.OMICORN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PI() { return GetToken(WandlabParser.PI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SIGMA() { return GetToken(WandlabParser.SIGMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OMEGA() { return GetToken(WandlabParser.OMEGA, 0); }
		public OpContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_op; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitOp(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOp(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OpContext op() {
		OpContext _localctx = new OpContext(Context, State);
		EnterRule(_localctx, 4, RULE_op);
		try {
			State = 77;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ALPHA:
				EnterOuterAlt(_localctx, 1);
				{
				State = 37;
				Match(ALPHA);
				}
				break;
			case BETA:
				EnterOuterAlt(_localctx, 2);
				{
				State = 38;
				Match(BETA);
				}
				break;
			case DELTA:
				EnterOuterAlt(_localctx, 3);
				{
				State = 39;
				Match(DELTA);
				State = 40;
				Match(PIPE);
				State = 41;
				Match(ARGUMENT);
				}
				break;
			case ZETA:
				EnterOuterAlt(_localctx, 4);
				{
				State = 42;
				Match(ZETA);
				State = 43;
				Match(PIPE);
				State = 44;
				Match(ARGUMENT);
				State = 45;
				Match(PIPE);
				State = 46;
				Match(ARGUMENT);
				}
				break;
			case ETA:
				EnterOuterAlt(_localctx, 5);
				{
				State = 47;
				Match(ETA);
				State = 48;
				Match(PIPE);
				State = 49;
				Match(ARGUMENT);
				State = 50;
				Match(PIPE);
				State = 51;
				Match(ARGUMENT);
				}
				break;
			case LAMBDA:
				EnterOuterAlt(_localctx, 6);
				{
				State = 52;
				Match(LAMBDA);
				State = 53;
				function();
				}
				break;
			case MU:
				EnterOuterAlt(_localctx, 7);
				{
				State = 54;
				Match(MU);
				State = 55;
				Match(PIPE);
				State = 56;
				Match(ARGUMENT);
				State = 57;
				Match(PIPE);
				State = 58;
				Match(ARGUMENT);
				}
				break;
			case XI:
				EnterOuterAlt(_localctx, 8);
				{
				State = 59;
				Match(XI);
				State = 60;
				Match(PIPE);
				State = 61;
				Match(ARGUMENT);
				State = 62;
				Match(PIPE);
				State = 63;
				Match(ARGUMENT);
				}
				break;
			case OMICORN:
				EnterOuterAlt(_localctx, 9);
				{
				State = 64;
				Match(OMICORN);
				State = 65;
				Match(PIPE);
				State = 66;
				Match(ARGUMENT);
				}
				break;
			case PI:
				EnterOuterAlt(_localctx, 10);
				{
				State = 67;
				Match(PI);
				State = 68;
				Match(PIPE);
				State = 69;
				Match(ARGUMENT);
				State = 70;
				Match(PIPE);
				State = 71;
				Match(ARGUMENT);
				}
				break;
			case SIGMA:
				EnterOuterAlt(_localctx, 11);
				{
				State = 72;
				Match(SIGMA);
				State = 73;
				function();
				}
				break;
			case OMEGA:
				EnterOuterAlt(_localctx, 12);
				{
				State = 74;
				Match(OMEGA);
				State = 75;
				Match(PIPE);
				State = 76;
				Match(ARGUMENT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(WandlabParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext[] operation() {
			return GetRuleContexts<OperationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public OperationContext operation(int i) {
			return GetRuleContext<OperationContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(WandlabParser.RBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DASH() { return GetTokens(WandlabParser.DASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DASH(int i) {
			return GetToken(WandlabParser.DASH, i);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 6, RULE_function);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			Match(LBRACKET);
			State = 80;
			operation();
			State = 85;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DASH) {
				{
				{
				State = 81;
				Match(DASH);
				State = 82;
				operation();
				}
				}
				State = 87;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 88;
			Match(RBRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SubopContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TICK() { return GetToken(WandlabParser.TICK, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode GAMMA() { return GetToken(WandlabParser.GAMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE() { return GetToken(WandlabParser.PIPE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARGUMENT() { return GetToken(WandlabParser.ARGUMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAU() { return GetToken(WandlabParser.TAU, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PHI() { return GetToken(WandlabParser.PHI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHI() { return GetToken(WandlabParser.CHI, 0); }
		public SubopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_subop; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterSubop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitSubop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSubop(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SubopContext subop() {
		SubopContext _localctx = new SubopContext(Context, State);
		EnterRule(_localctx, 8, RULE_subop);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			Match(TICK);
			State = 99;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case GAMMA:
				{
				State = 91;
				Match(GAMMA);
				State = 92;
				Match(PIPE);
				State = 93;
				Match(ARGUMENT);
				}
				break;
			case TAU:
				{
				State = 94;
				Match(TAU);
				State = 95;
				Match(PIPE);
				State = 96;
				Match(ARGUMENT);
				}
				break;
			case PHI:
				{
				State = 97;
				Match(PHI);
				}
				break;
			case CHI:
				{
				State = 98;
				Match(CHI);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Preprocessor_commandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POUND() { return GetToken(WandlabParser.POUND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PREPROCESSNAME() { return GetToken(WandlabParser.PREPROCESSNAME, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(WandlabParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PREPROCESSARG() { return GetTokens(WandlabParser.PREPROCESSARG); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PREPROCESSARG(int i) {
			return GetToken(WandlabParser.PREPROCESSARG, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(WandlabParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PIPE() { return GetTokens(WandlabParser.PIPE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PIPE(int i) {
			return GetToken(WandlabParser.PIPE, i);
		}
		public Preprocessor_commandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_preprocessor_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.EnterPreprocessor_command(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IWandlabListener typedListener = listener as IWandlabListener;
			if (typedListener != null) typedListener.ExitPreprocessor_command(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IWandlabVisitor<TResult> typedVisitor = visitor as IWandlabVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPreprocessor_command(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Preprocessor_commandContext preprocessor_command() {
		Preprocessor_commandContext _localctx = new Preprocessor_commandContext(Context, State);
		EnterRule(_localctx, 10, RULE_preprocessor_command);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			Match(POUND);
			State = 102;
			Match(PREPROCESSNAME);
			State = 103;
			Match(COLON);
			State = 104;
			Match(PREPROCESSARG);
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PIPE) {
				{
				{
				State = 105;
				Match(PIPE);
				State = 106;
				Match(PREPROCESSARG);
				}
				}
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 112;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '%', 'u', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', '\t', 
		'\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', '\x6', 
		'\t', '\x6', '\x4', '\a', '\t', '\a', '\x3', '\x2', '\a', '\x2', '\x10', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x13', '\v', '\x2', '\x3', '\x2', 
		'\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x18', '\n', '\x2', '\f', '\x2', 
		'\xE', '\x2', '\x1B', '\v', '\x2', '\a', '\x2', '\x1D', '\n', '\x2', '\f', 
		'\x2', '\xE', '\x2', ' ', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x5', '\x3', '&', '\n', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x5', '\x4', 'P', '\n', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 
		'V', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'Y', '\v', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', '\x66', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\a', '\a', 'n', '\n', '\a', 
		'\f', '\a', '\xE', '\a', 'q', '\v', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x2', '\x2', '\b', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\x2', 
		'\x2', '\x2', '\x82', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x4', 
		'#', '\x3', '\x2', '\x2', '\x2', '\x6', 'O', '\x3', '\x2', '\x2', '\x2', 
		'\b', 'Q', '\x3', '\x2', '\x2', '\x2', '\n', '\\', '\x3', '\x2', '\x2', 
		'\x2', '\f', 'g', '\x3', '\x2', '\x2', '\x2', '\xE', '\x10', '\x5', '\f', 
		'\a', '\x2', '\xF', '\xE', '\x3', '\x2', '\x2', '\x2', '\x10', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x11', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x12', '\x3', '\x2', '\x2', '\x2', '\x12', '\x1E', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\x11', '\x3', '\x2', '\x2', '\x2', '\x14', '\x19', 
		'\x5', '\x4', '\x3', '\x2', '\x15', '\x16', '\a', '\x1A', '\x2', '\x2', 
		'\x16', '\x18', '\x5', '\x4', '\x3', '\x2', '\x17', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x19', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x1C', '\x14', '\x3', '\x2', '\x2', '\x2', '\x1D', ' ', 
		'\x3', '\x2', '\x2', '\x2', '\x1E', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\x1E', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x1F', '!', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\x1E', '\x3', '\x2', '\x2', '\x2', '!', '\"', '\a', 
		'\x2', '\x2', '\x3', '\"', '\x3', '\x3', '\x2', '\x2', '\x2', '#', '%', 
		'\x5', '\x6', '\x4', '\x2', '$', '&', '\x5', '\n', '\x6', '\x2', '%', 
		'$', '\x3', '\x2', '\x2', '\x2', '%', '&', '\x3', '\x2', '\x2', '\x2', 
		'&', '\x5', '\x3', '\x2', '\x2', '\x2', '\'', 'P', '\a', '\b', '\x2', 
		'\x2', '(', 'P', '\a', '\t', '\x2', '\x2', ')', '*', '\a', '\n', '\x2', 
		'\x2', '*', '+', '\a', '\x1F', '\x2', '\x2', '+', 'P', '\a', '\x3', '\x2', 
		'\x2', ',', '-', '\a', '\v', '\x2', '\x2', '-', '.', '\a', '\x1F', '\x2', 
		'\x2', '.', '/', '\a', '\x3', '\x2', '\x2', '/', '\x30', '\a', '\x1F', 
		'\x2', '\x2', '\x30', 'P', '\a', '\x3', '\x2', '\x2', '\x31', '\x32', 
		'\a', '\f', '\x2', '\x2', '\x32', '\x33', '\a', '\x1F', '\x2', '\x2', 
		'\x33', '\x34', '\a', '\x3', '\x2', '\x2', '\x34', '\x35', '\a', '\x1F', 
		'\x2', '\x2', '\x35', 'P', '\a', '\x3', '\x2', '\x2', '\x36', '\x37', 
		'\a', '\r', '\x2', '\x2', '\x37', 'P', '\x5', '\b', '\x5', '\x2', '\x38', 
		'\x39', '\a', '\xE', '\x2', '\x2', '\x39', ':', '\a', '\x1F', '\x2', '\x2', 
		':', ';', '\a', '\x3', '\x2', '\x2', ';', '<', '\a', '\x1F', '\x2', '\x2', 
		'<', 'P', '\a', '\x3', '\x2', '\x2', '=', '>', '\a', '\xF', '\x2', '\x2', 
		'>', '?', '\a', '\x1F', '\x2', '\x2', '?', '@', '\a', '\x3', '\x2', '\x2', 
		'@', '\x41', '\a', '\x1F', '\x2', '\x2', '\x41', 'P', '\a', '\x3', '\x2', 
		'\x2', '\x42', '\x43', '\a', '\x10', '\x2', '\x2', '\x43', '\x44', '\a', 
		'\x1F', '\x2', '\x2', '\x44', 'P', '\a', '\x3', '\x2', '\x2', '\x45', 
		'\x46', '\a', '\x11', '\x2', '\x2', '\x46', 'G', '\a', '\x1F', '\x2', 
		'\x2', 'G', 'H', '\a', '\x3', '\x2', '\x2', 'H', 'I', '\a', '\x1F', '\x2', 
		'\x2', 'I', 'P', '\a', '\x3', '\x2', '\x2', 'J', 'K', '\a', '\x12', '\x2', 
		'\x2', 'K', 'P', '\x5', '\b', '\x5', '\x2', 'L', 'M', '\a', '\x13', '\x2', 
		'\x2', 'M', 'N', '\a', '\x1F', '\x2', '\x2', 'N', 'P', '\a', '\x3', '\x2', 
		'\x2', 'O', '\'', '\x3', '\x2', '\x2', '\x2', 'O', '(', '\x3', '\x2', 
		'\x2', '\x2', 'O', ')', '\x3', '\x2', '\x2', '\x2', 'O', ',', '\x3', '\x2', 
		'\x2', '\x2', 'O', '\x31', '\x3', '\x2', '\x2', '\x2', 'O', '\x36', '\x3', 
		'\x2', '\x2', '\x2', 'O', '\x38', '\x3', '\x2', '\x2', '\x2', 'O', '=', 
		'\x3', '\x2', '\x2', '\x2', 'O', '\x42', '\x3', '\x2', '\x2', '\x2', 'O', 
		'\x45', '\x3', '\x2', '\x2', '\x2', 'O', 'J', '\x3', '\x2', '\x2', '\x2', 
		'O', 'L', '\x3', '\x2', '\x2', '\x2', 'P', '\a', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'R', '\a', '#', '\x2', '\x2', 'R', 'W', '\x5', '\x4', '\x3', 
		'\x2', 'S', 'T', '\a', '\x1A', '\x2', '\x2', 'T', 'V', '\x5', '\x4', '\x3', 
		'\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 'V', 'Y', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'U', '\x3', '\x2', '\x2', '\x2', 'W', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Z', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '[', '\a', '$', '\x2', '\x2', '[', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\\', '\x65', '\a', ' ', '\x2', '\x2', ']', '^', '\a', '\x14', 
		'\x2', '\x2', '^', '_', '\a', '\x1F', '\x2', '\x2', '_', '\x66', '\a', 
		'\x3', '\x2', '\x2', '`', '\x61', '\a', '\x15', '\x2', '\x2', '\x61', 
		'\x62', '\a', '\x1F', '\x2', '\x2', '\x62', '\x66', '\a', '\x3', '\x2', 
		'\x2', '\x63', '\x66', '\a', '\x16', '\x2', '\x2', '\x64', '\x66', '\a', 
		'\x17', '\x2', '\x2', '\x65', ']', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x65', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x64', '\x3', '\x2', '\x2', '\x2', '\x66', '\v', '\x3', 
		'\x2', '\x2', '\x2', 'g', 'h', '\a', '\x1C', '\x2', '\x2', 'h', 'i', '\a', 
		'\x18', '\x2', '\x2', 'i', 'j', '\a', '\x1D', '\x2', '\x2', 'j', 'o', 
		'\a', '\x19', '\x2', '\x2', 'k', 'l', '\a', '\x1F', '\x2', '\x2', 'l', 
		'n', '\a', '\x19', '\x2', '\x2', 'm', 'k', '\x3', '\x2', '\x2', '\x2', 
		'n', 'q', '\x3', '\x2', '\x2', '\x2', 'o', 'm', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\x3', '\x2', '\x2', '\x2', 'p', 'r', '\x3', '\x2', '\x2', '\x2', 
		'q', 'o', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\a', '\x1E', '\x2', '\x2', 
		's', '\r', '\x3', '\x2', '\x2', '\x2', '\n', '\x11', '\x19', '\x1E', '%', 
		'O', 'W', '\x65', 'o',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
