//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Wandlab.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="WandlabParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IWandlabListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="WandlabParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] WandlabParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WandlabParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] WandlabParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WandlabParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] WandlabParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WandlabParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] WandlabParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WandlabParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp([NotNull] WandlabParser.OpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WandlabParser.op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp([NotNull] WandlabParser.OpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WandlabParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] WandlabParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WandlabParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] WandlabParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="WandlabParser.subop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubop([NotNull] WandlabParser.SubopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="WandlabParser.subop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubop([NotNull] WandlabParser.SubopContext context);
}
