//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\Wandlab.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public partial class WandlabLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		ARGUMENT=1, STRING=2, POINTER=3, NUMBER=4, COMMENT=5, ALPHA=6, BETA=7, 
		DELTA=8, ZETA=9, ETA=10, LAMBDA=11, MU=12, XI=13, OMICORN=14, PI=15, SIGMA=16, 
		OMEGA=17, GAMMA=18, TAU=19, PHI=20, CHI=21, PREPROCESSNAME=22, PREPROCESSARG=23, 
		DASH=24, SLASH=25, POUND=26, COLON=27, SEMICOLON=28, PIPE=29, TICK=30, 
		QUOTE=31, ARROW=32, LBRACKET=33, RBRACKET=34, WS=35;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", "ALPHA", "BETA", 
		"DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICORN", "PI", "SIGMA", 
		"OMEGA", "GAMMA", "TAU", "PHI", "CHI", "PREPROCESSNAME", "PREPROCESSARG", 
		"DASH", "SLASH", "POUND", "COLON", "SEMICOLON", "PIPE", "TICK", "QUOTE", 
		"ARROW", "LBRACKET", "RBRACKET", "WS"
	};


	public WandlabLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public WandlabLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, "'Alpha'", "'Beta'", "'Delta'", "'Zeta'", 
		"'Eta'", "'Lambda'", "'Mu'", "'Xi'", "'Omicorn'", "'Pi'", "'Sigma'", "'Omega'", 
		"'Gamma'", "'Tau'", "'Phi'", "'Chi'", null, null, "'-'", "'/'", "'#'", 
		"':'", "';'", "'|'", "'^'", "'\"'", "'->'", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "ARGUMENT", "STRING", "POINTER", "NUMBER", "COMMENT", "ALPHA", "BETA", 
		"DELTA", "ZETA", "ETA", "LAMBDA", "MU", "XI", "OMICORN", "PI", "SIGMA", 
		"OMEGA", "GAMMA", "TAU", "PHI", "CHI", "PREPROCESSNAME", "PREPROCESSARG", 
		"DASH", "SLASH", "POUND", "COLON", "SEMICOLON", "PIPE", "TICK", "QUOTE", 
		"ARROW", "LBRACKET", "RBRACKET", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Wandlab.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static WandlabLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '%', '\xE2', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x5', '\x2', 'M', '\n', '\x2', '\x3', '\x3', '\x3', '\x3', '\a', 
		'\x3', 'Q', '\n', '\x3', '\f', '\x3', '\xE', '\x3', 'T', '\v', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x6', '\x4', 'Y', '\n', '\x4', 
		'\r', '\x4', '\xE', '\x4', 'Z', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x6', '\x5', '`', '\n', '\x5', '\r', '\x5', '\xE', '\x5', '\x61', '\x3', 
		'\x6', '\x3', '\x6', '\a', '\x6', '\x66', '\n', '\x6', '\f', '\x6', '\xE', 
		'\x6', 'i', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x6', '\x17', '\xC0', '\n', 
		'\x17', '\r', '\x17', '\xE', '\x17', '\xC1', '\x3', '\x18', '\x3', '\x18', 
		'\x5', '\x18', '\xC6', '\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', '!', '\x3', '!', 
		'\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', '$', 
		'\x3', '$', '\x3', '$', '\x3', '$', '\x4', 'R', 'g', '\x2', '%', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', 
		'\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', 
		'\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', 
		'/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', 
		'\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x41', '\"', '\x43', 
		'#', '\x45', '$', 'G', '%', '\x3', '\x2', '\x5', '\x3', '\x2', '\x32', 
		';', '\x4', '\x2', '\x43', '\\', '\x61', '\x61', '\x5', '\x2', '\v', '\f', 
		'\xF', '\xF', '\"', '\"', '\x2', '\xE9', '\x2', '\x3', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'G', '\x3', '\x2', '\x2', '\x2', '\x3', 'L', '\x3', '\x2', '\x2', '\x2', 
		'\x5', 'N', '\x3', '\x2', '\x2', '\x2', '\a', 'X', '\x3', '\x2', '\x2', 
		'\x2', '\t', '_', '\x3', '\x2', '\x2', '\x2', '\v', '\x63', '\x3', '\x2', 
		'\x2', '\x2', '\r', 'n', '\x3', '\x2', '\x2', '\x2', '\xF', 't', '\x3', 
		'\x2', '\x2', '\x2', '\x11', 'y', '\x3', '\x2', '\x2', '\x2', '\x13', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', '\x15', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '\x88', '\x3', '\x2', '\x2', '\x2', '\x19', '\x8F', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x92', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '!', '\xA0', '\x3', '\x2', '\x2', '\x2', '#', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '%', '\xAC', '\x3', '\x2', '\x2', '\x2', '\'', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', ')', '\xB6', '\x3', '\x2', '\x2', '\x2', '+', '\xBA', 
		'\x3', '\x2', '\x2', '\x2', '-', '\xBF', '\x3', '\x2', '\x2', '\x2', '/', 
		'\xC5', '\x3', '\x2', '\x2', '\x2', '\x31', '\xC7', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\xC9', '\x3', '\x2', '\x2', '\x2', '\x35', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\xCD', '\x3', '\x2', '\x2', '\x2', '\x39', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', ';', '\xD1', '\x3', '\x2', '\x2', 
		'\x2', '=', '\xD3', '\x3', '\x2', '\x2', '\x2', '?', '\xD5', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\xD7', '\x3', '\x2', '\x2', '\x2', '\x43', '\xDA', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\xDC', '\x3', '\x2', '\x2', '\x2', 
		'G', '\xDE', '\x3', '\x2', '\x2', '\x2', 'I', 'M', '\x5', '\x5', '\x3', 
		'\x2', 'J', 'M', '\x5', '\a', '\x4', '\x2', 'K', 'M', '\x5', '\t', '\x5', 
		'\x2', 'L', 'I', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'K', '\x3', '\x2', '\x2', '\x2', 'M', '\x4', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'R', '\x5', '?', ' ', '\x2', 'O', 'Q', '\v', '\x2', 
		'\x2', '\x2', 'P', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'T', '\x3', '\x2', 
		'\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'U', '\x3', '\x2', '\x2', '\x2', 'T', 'R', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'V', '\x5', '?', ' ', '\x2', 'V', '\x6', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'Y', '\x5', '\x41', '!', '\x2', 'X', 'W', '\x3', '\x2', 
		'\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', 'X', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '[', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\x3', 
		'\x2', '\x2', '\x2', '\\', ']', '\x5', '\t', '\x5', '\x2', ']', '\b', 
		'\x3', '\x2', '\x2', '\x2', '^', '`', '\t', '\x2', '\x2', '\x2', '_', 
		'^', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x61', '_', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\n', '\x3', '\x2', '\x2', '\x2', '\x63', 'g', '\x5', 
		'\x33', '\x1A', '\x2', '\x64', '\x66', '\v', '\x2', '\x2', '\x2', '\x65', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x66', 'i', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 'g', '\x65', '\x3', '\x2', 
		'\x2', '\x2', 'h', 'j', '\x3', '\x2', '\x2', '\x2', 'i', 'g', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\x5', '\x33', '\x1A', '\x2', 'k', 'l', '\x3', 
		'\x2', '\x2', '\x2', 'l', 'm', '\b', '\x6', '\x2', '\x2', 'm', '\f', '\x3', 
		'\x2', '\x2', '\x2', 'n', 'o', '\a', '\x43', '\x2', '\x2', 'o', 'p', '\a', 
		'n', '\x2', '\x2', 'p', 'q', '\a', 'r', '\x2', '\x2', 'q', 'r', '\a', 
		'j', '\x2', '\x2', 'r', 's', '\a', '\x63', '\x2', '\x2', 's', '\xE', '\x3', 
		'\x2', '\x2', '\x2', 't', 'u', '\a', '\x44', '\x2', '\x2', 'u', 'v', '\a', 
		'g', '\x2', '\x2', 'v', 'w', '\a', 'v', '\x2', '\x2', 'w', 'x', '\a', 
		'\x63', '\x2', '\x2', 'x', '\x10', '\x3', '\x2', '\x2', '\x2', 'y', 'z', 
		'\a', '\x46', '\x2', '\x2', 'z', '{', '\a', 'g', '\x2', '\x2', '{', '|', 
		'\a', 'n', '\x2', '\x2', '|', '}', '\a', 'v', '\x2', '\x2', '}', '~', 
		'\a', '\x63', '\x2', '\x2', '~', '\x12', '\x3', '\x2', '\x2', '\x2', '\x7F', 
		'\x80', '\a', '\\', '\x2', '\x2', '\x80', '\x81', '\a', 'g', '\x2', '\x2', 
		'\x81', '\x82', '\a', 'v', '\x2', '\x2', '\x82', '\x83', '\a', '\x63', 
		'\x2', '\x2', '\x83', '\x14', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', 
		'\a', 'G', '\x2', '\x2', '\x85', '\x86', '\a', 'v', '\x2', '\x2', '\x86', 
		'\x87', '\a', '\x63', '\x2', '\x2', '\x87', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x88', '\x89', '\a', 'N', '\x2', '\x2', '\x89', '\x8A', '\a', 
		'\x63', '\x2', '\x2', '\x8A', '\x8B', '\a', 'o', '\x2', '\x2', '\x8B', 
		'\x8C', '\a', '\x64', '\x2', '\x2', '\x8C', '\x8D', '\a', '\x66', '\x2', 
		'\x2', '\x8D', '\x8E', '\a', '\x63', '\x2', '\x2', '\x8E', '\x18', '\x3', 
		'\x2', '\x2', '\x2', '\x8F', '\x90', '\a', 'O', '\x2', '\x2', '\x90', 
		'\x91', '\a', 'w', '\x2', '\x2', '\x91', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x92', '\x93', '\a', 'Z', '\x2', '\x2', '\x93', '\x94', '\a', 
		'k', '\x2', '\x2', '\x94', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x96', '\a', 'Q', '\x2', '\x2', '\x96', '\x97', '\a', 'o', '\x2', '\x2', 
		'\x97', '\x98', '\a', 'k', '\x2', '\x2', '\x98', '\x99', '\a', '\x65', 
		'\x2', '\x2', '\x99', '\x9A', '\a', 'q', '\x2', '\x2', '\x9A', '\x9B', 
		'\a', 't', '\x2', '\x2', '\x9B', '\x9C', '\a', 'p', '\x2', '\x2', '\x9C', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', 'R', '\x2', 
		'\x2', '\x9E', '\x9F', '\a', 'k', '\x2', '\x2', '\x9F', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\xA0', '\xA1', '\a', 'U', '\x2', '\x2', '\xA1', '\xA2', 
		'\a', 'k', '\x2', '\x2', '\xA2', '\xA3', '\a', 'i', '\x2', '\x2', '\xA3', 
		'\xA4', '\a', 'o', '\x2', '\x2', '\xA4', '\xA5', '\a', '\x63', '\x2', 
		'\x2', '\xA5', '\"', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\a', 
		'Q', '\x2', '\x2', '\xA7', '\xA8', '\a', 'o', '\x2', '\x2', '\xA8', '\xA9', 
		'\a', 'g', '\x2', '\x2', '\xA9', '\xAA', '\a', 'i', '\x2', '\x2', '\xAA', 
		'\xAB', '\a', '\x63', '\x2', '\x2', '\xAB', '$', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAD', '\a', 'I', '\x2', '\x2', '\xAD', '\xAE', '\a', 
		'\x63', '\x2', '\x2', '\xAE', '\xAF', '\a', 'o', '\x2', '\x2', '\xAF', 
		'\xB0', '\a', 'o', '\x2', '\x2', '\xB0', '\xB1', '\a', '\x63', '\x2', 
		'\x2', '\xB1', '&', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\a', 
		'V', '\x2', '\x2', '\xB3', '\xB4', '\a', '\x63', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', 'w', '\x2', '\x2', '\xB5', '(', '\x3', '\x2', '\x2', '\x2', 
		'\xB6', '\xB7', '\a', 'R', '\x2', '\x2', '\xB7', '\xB8', '\a', 'j', '\x2', 
		'\x2', '\xB8', '\xB9', '\a', 'k', '\x2', '\x2', '\xB9', '*', '\x3', '\x2', 
		'\x2', '\x2', '\xBA', '\xBB', '\a', '\x45', '\x2', '\x2', '\xBB', '\xBC', 
		'\a', 'j', '\x2', '\x2', '\xBC', '\xBD', '\a', 'k', '\x2', '\x2', '\xBD', 
		',', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xC0', '\t', '\x3', '\x2', '\x2', 
		'\xBF', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\x3', '\x2', 
		'\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', 
		'\x3', '\x2', '\x2', '\x2', '\xC2', '.', '\x3', '\x2', '\x2', '\x2', '\xC3', 
		'\xC6', '\x5', '\x5', '\x3', '\x2', '\xC4', '\xC6', '\x5', '\t', '\x5', 
		'\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '\xC6', '\x30', '\x3', '\x2', '\x2', '\x2', '\xC7', 
		'\xC8', '\a', '/', '\x2', '\x2', '\xC8', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\xC9', '\xCA', '\a', '\x31', '\x2', '\x2', '\xCA', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\a', '%', '\x2', '\x2', '\xCC', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\a', '<', '\x2', 
		'\x2', '\xCE', '\x38', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\a', 
		'=', '\x2', '\x2', '\xD0', ':', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD2', 
		'\a', '~', '\x2', '\x2', '\xD2', '<', '\x3', '\x2', '\x2', '\x2', '\xD3', 
		'\xD4', '\a', '`', '\x2', '\x2', '\xD4', '>', '\x3', '\x2', '\x2', '\x2', 
		'\xD5', '\xD6', '\a', '$', '\x2', '\x2', '\xD6', '@', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\xD8', '\a', '/', '\x2', '\x2', '\xD8', '\xD9', '\a', 
		'@', '\x2', '\x2', '\xD9', '\x42', '\x3', '\x2', '\x2', '\x2', '\xDA', 
		'\xDB', '\a', ']', '\x2', '\x2', '\xDB', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\xDC', '\xDD', '\a', '_', '\x2', '\x2', '\xDD', '\x46', '\x3', 
		'\x2', '\x2', '\x2', '\xDE', '\xDF', '\t', '\x4', '\x2', '\x2', '\xDF', 
		'\xE0', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\b', '$', '\x2', 
		'\x2', '\xE1', 'H', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', 'L', 'R', 
		'Z', '\x61', 'g', '\xC1', '\xC5', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
